{
 "title": "National Dashboard - Complain (District Wise)",
 "time": { "from": "now/d-8h", "to": "now/d+1d-8h-1d" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "district",
    "label": "District",
    "query": "SELECT name FROM common_district order by name asc;"
   },
   {
    "name": "IncidentType",
    "label": "Incident Type",
    "query": "SELECT incidentType FROM incidents_incident group by incidentType"
   }
  ]
 },
 "panels": [
  {
   "title": "INCIDENTS FOR THE GIVEN TIME RANGE",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "TOTAL",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "select\ncount(*)\nfrom incidents_incident ins\ninner join common_district cd on cd.code = ins.district and cd.name in ($district) \nwhere    $__timeFilter(ins.created_date) and ins.incidentType in ($IncidentType)"
    }
   ]
  },
  {
   "title": "NEW ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "select count(*) as value\nfrom incidents_incident inc\ninner join common_district cd on cd.code = inc.district and cd.name in ($district)\nwhere  inc.current_status = 'NEW'  and  $__timeFilter(inc.created_date)  and inc.incidentType in ($IncidentType)\nGROUP BY inc.current_status"
    }
   ]
  },
  {
   "title": "IN-PROGRESS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "select count(*) as value\nfrom incidents_incident inc\ninner join common_district cd on cd.code = inc.district and cd.name in ($district)\nwhere \n(inc.current_status = 'ACTION_TAKEN' or  \ninc.current_status = 'ACTION_PENDING' or \ninc.current_status = 'ADVICE_PROVIDED' or \ninc.current_status = 'ADVICE_REQESTED' or\ninc.current_status = 'VERIFIED' ) and \n$__timeFilter(inc.created_date)   and inc.incidentType in ($IncidentType)\n\n-- GROUP BY id"
    }
   ]
  },
  {
   "title": "CLOSED",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "select count(*) as value\nfrom incidents_incident inc\ninner join common_district cd on cd.code = inc.district and cd.name in ($district)\nwhere (inc.current_status = 'CLOSED' || inc.current_status =  'INVALIDATED') and $__timeFilter(inc.created_date)  and inc.incidentType in ($IncidentType)\n-- GROUP BY inc.current_status"
    }
   ]
  },
  {
   "title": "UN-ASSIGNED",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "\nselect T.Total - ( T.VERIFIED + T.NEW + T.INVALIDATED + T.CLOSED + T.ADVICE_REQESTED + T.ACTION_TAKEN + T.ACTION_PENDING ) as val\nfrom\n(select   inc.created_date as \"time\", \n sum(( CASE WHEN  inc.current_status  = 'VERIFIED' THEN 1 ELSE 0 END) ) As 'VERIFIED',\nSUM(( CASE WHEN inc.current_status = 'NEW' THEN 1 ELSE 0 END )) AS 'NEW',\nSUM( CASE WHEN inc.current_status = 'INVALIDATED' THEN 1 ELSE 0 END ) AS 'INVALIDATED',\nSUM( CASE WHEN inc.current_status = 'CLOSED' THEN 1 ELSE 0 END ) AS 'CLOSED',\nSUM( CASE WHEN inc.current_status = 'ADVICE_REQESTED' THEN 1 ELSE 0  END ) AS 'ADVICE_REQESTED',\nSUM( CASE WHEN inc.current_status = 'ACTION_TAKEN' THEN 1 ELSE 0  END ) AS 'ACTION_TAKEN',\nSUM( CASE WHEN inc.current_status = 'ACTION_PENDING' THEN 1 ELSE 0  END ) AS 'ACTION_PENDING', \nSUM( CASE WHEN inc.current_status = 'ADVICE_PROVIDED' THEN 1 ELSE 0  END ) AS 'ADVICE_PROVIDED',\ncount(*) as 'Total' \nfrom incidents_incident inc\ninner join common_district cd on cd.code = inc.district and cd.name in ($district)\nwhere $__timeFilter(inc.created_date)   and inc.incidentType in ($IncidentType) ) as T \n\n"
    }
   ]
  },
  {
   "title": "VIOLATION OF ELECTION LAW: TOP 5 SUBCATEGORIES",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT UNIX_TIMESTAMP(ins.created_date) AS time_sec, CONCAT( common_category.code,' | ',sub_category) as metric,count(ins.id) as value\nfrom incidents_incident ins INNER JOIN common_category ON\ncommon_category.id = ins.category\ninner join common_district cd on cd.code = ins.district and cd.name in ($district)\nwhere\n  $__timeFilter(ins.created_date) and \n  common_category.top_category=\"Violation of election law\"   and ins.incidentType in ($IncidentType)\nGROUP by common_category.code\norder by value desc, common_category.code \nlimit 5\n"
    }
   ]
  },
  {
   "title": "VIOLENCE: TOP 5 SUBCATEGORIES",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT UNIX_TIMESTAMP(inc.created_date) AS time_sec, CONCAT( common_category.code,' | ',sub_category) as metric,count(inc.id) as value\nfrom incidents_incident inc INNER JOIN common_category ON\ncommon_category.id = inc.category\ninner join common_district cd on cd.code = inc.district and cd.name in ($district)\nwhere\n  $__timeFilter(inc.created_date) and \n  common_category.top_category=\"Violence\"  and inc.incidentType in ($IncidentType)\nGROUP by common_category.code\norder by value desc, common_category.code \nlimit 5\n"
    }
   ]
  },
  {
   "title": "NO. OF INCIDENTS BY MODE",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 4 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeFilter(date_time) as time_sec,\n  mode_of_recieve AS metric,\n  count(mode_of_recieve) AS \"mode_of_recieve\"\nFROM (select occured_date  as date_time , common_channel.name as mode_of_recieve from incidents_incident inc\ninner join common_channel on inc.infoChannel = common_channel.id \ninner join common_district cd on cd.code = inc.district and cd.name in ($district)\nwhere\n  $__timeFilter(occured_date)  and inc.incidentType in ($IncidentType)) as real_data\nGROUP BY 1,2"
    }
   ]
  },
  {
   "title": "NO. OF INCIDENTS BY SEVERITY LEVEL",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select\nUNIX_TIMESTAMP(ins.occured_date) as time_sec,\ncount(ins.id),'Low (1-3)' as metric\nfrom \nincidents_incident as ins\ninner join common_district cd on cd.code = ins.district and cd.name in ($district)\nwhere\n  $__timeFilter(ins.occured_date) and  severity<4  and ins.incidentType in ($IncidentType)\ngroup by ins.id\n"
    },
    {
     "rawSql": "select\nUNIX_TIMESTAMP(ins.occured_date) as time_sec,\ncount(ins.id),'Medium (4-7)' as metric\nfrom \nincidents_incident as ins\ninner join common_district cd on cd.code = ins.district and cd.name in ($district)\nwhere\n  $__timeFilter(ins.occured_date) and  severity>3 and severity<8  and ins.incidentType in ($IncidentType)\ngroup by ins.id\n"
    },
    {
     "rawSql": "select\nUNIX_TIMESTAMP(ins.occured_date) as time_sec,\ncount(ins.id),'High (8-10)' as metric\nfrom \nincidents_incident as ins\ninner join common_district cd on cd.code = ins.district and cd.name in ($district)\nwhere\n  $__timeFilter(ins.occured_date) and  severity>7  and ins.incidentType in ($IncidentType)\ngroup by ins.id\n"
    }
   ]
  },
  {
   "title": "OTHER CATEGORY",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 10 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT now() as 'time',\ncount(inc.id) \nfrom incidents_incident inc \nINNER JOIN common_category ON common_category.id = inc.category\ninner join common_district cd on cd.code = inc.district and cd.name in ($district)\nwhere\n  $__timeFilter(inc.created_date) and inc.category = NULL and inc.incidentType in ($IncidentType)\n\n"
    }
   ]
  },
  {
   "title": "UN-ASSIGNED MODE",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select now() as 'time',count(*) as value\n--   count(CASE WHEN current_status != 'RESOLVED' then 'Unresolved' end) as Unresolved,\nfrom incidents_incident inc\ninner join common_district cd on cd.code = inc.district and cd.name in ($district)\nwhere \n  ( inc.category is null or inc.category = '' )\n  AND \n  $__timeFilter(inc.created_date)  and inc.incidentType in ($IncidentType)"
    }
   ]
  },
  { "title": "ALL INCIDENTS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "TOTAL",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "select count(*) as val\nfrom incidents_incident inc\ninner join common_district cd on cd.code = inc.district and cd.name in ($district)  and inc.incidentType in ($IncidentType)"
    }
   ]
  },
  {
   "title": "NEW ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 16 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "select count(*) as val\nfrom incidents_incident inc\ninner join common_district cd on cd.code = inc.district and cd.name in ($district)\nwhere  inc.current_status = 'NEW'  and inc.incidentType in ($IncidentType)\n-- GROUP BY inc.current_status"
    }
   ]
  },
  {
   "title": "IN-PROGRESS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 16 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "select count(*) as value\nfrom incidents_incident inc\ninner join common_district cd on cd.code = inc.district and cd.name in ($district)\nwhere \n(inc.current_status = 'ACTION_TAKEN' or  \ninc.current_status = 'ACTION_PENDING' or \ninc.current_status = 'ADVICE_PROVIDED' or \ninc.current_status = 'ADVICE_REQESTED' or\ninc.current_status = 'VERIFIED' )   and inc.incidentType in ($IncidentType)"
    }
   ]
  },
  {
   "title": "CLOSED",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 16 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "select count(*)\nfrom incidents_incident inc\ninner join common_district cd on cd.code = inc.district and cd.name in ($district)\nwhere (inc.current_status = 'CLOSED' || inc.current_status =  'INVALIDATED')   and inc.incidentType in ($IncidentType)\n-- GROUP BY current_status"
    }
   ]
  },
  {
   "title": "UN-ASSIGNED",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 16 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "select T.Total - ( T.VERIFIED + T.NEW + T.INVALIDATED + T.CLOSED + T.ADVICE_REQESTED + T.ACTION_TAKEN + T.ACTION_PENDING ) as val\nfrom\n(select   \n sum(( CASE WHEN  inc.current_status  = 'VERIFIED' THEN 1 ELSE 0 END) ) As 'VERIFIED',\nSUM(( CASE WHEN inc.current_status = 'NEW' THEN 1 ELSE 0 END )) AS 'NEW',\nSUM( CASE WHEN inc.current_status = 'INVALIDATED' THEN 1 ELSE 0 END ) AS 'INVALIDATED',\nSUM( CASE WHEN inc.current_status = 'CLOSED' THEN 1 ELSE 0 END ) AS 'CLOSED',\nSUM( CASE WHEN inc.current_status = 'ADVICE_REQESTED' THEN 1 ELSE 0  END ) AS 'ADVICE_REQESTED',\nSUM( CASE WHEN inc.current_status = 'ACTION_TAKEN' THEN 1 ELSE 0  END ) AS 'ACTION_TAKEN',\nSUM( CASE WHEN inc.current_status = 'ACTION_PENDING' THEN 1 ELSE 0  END ) AS 'ACTION_PENDING', \nSUM( CASE WHEN inc.current_status = 'ADVICE_PROVIDED' THEN 1 ELSE 0  END ) AS 'ADVICE_PROVIDED',\ncount(*) as 'Total' \nfrom incidents_incident inc\ninner join common_district cd on cd.code = inc.district and cd.name in ($district)   and inc.incidentType in ($IncidentType) ) as T "
    }
   ]
  }
 ]
}